config/routes.rb
Rails.application.routes.draw do
  resources :plates, only: %i[ index new create show ]
  get '/plates/:id/up', to: 'plates#up', as: 'up_plate'
  get '/plates/:id/new_img', to: 'plates#new_img', as: 'new_plate_image'
  post '/plates/:id/new_img', to: 'plates#add_new_img', as: 'add_new_plate_image'
  get '/static', to: 'static#get_lic_plate'
  get '/plate_img/:id/:num', to: 'static#get_additional_lic_plate'
  get '/blank_plate/:state', to: 'static#get_blank_plate'
  root 'plates#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plate.rb
class Plate < ApplicationRecord
  states = %w(AK AL AR AZ CA CO CT DC DE FL GA HI IA ID IL IN KS KY LA MA MD ME MI MN MO MS MT NC ND NE NH NJ NM NV NY OH OK OR PA RI SC SD TN TX UT VA VT WA WI WV WY)

  #validates :plate, length: { maximum: 7, minimum: 1 }
  #validates :plate, format: { without: /\s/, message: "can not contain spaces" }
  #validates :plate, format: { without: /[\W]/, message: "must only contain valid characters (A-Z 1-9)" }
  #validates :state, inclusion: { in: states, message: "must be a valid US state (NV, CA, NY ...)" }
  #validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plates_controller.rb
class PlatesController < ApplicationController
  before_action :set_plate, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token
  ITEMS_PER_PAGE = 25

  # GET /plates or /plates.json
  def index
    allowed_sorts = [:score, :score_least, :newest, :oldest]

    states = %w(AK AL AR AZ CA CO CT DC DE FL GA HI IA ID IL IN KS KY LA MA MD ME MI MN MO MS MT NC ND NE NH NJ NM NV NY OH OK OR PA RI SC SD TN TX UT VA VT WA WI WV WY)
    scopes = [:all] + states

    @sort_by = :newest
    @sort_by = params[:sort_by].to_sym if params[:sort_by] && allowed_sorts.include?(params[:sort_by].to_sym)

    @scope = :all
    @scope = params[:scope].to_sym if params[:scope] && scopes.include?(params[:scope])

    @query = ""
    @query = params[:query].upcase.gsub("0", "O") if params[:query]

    @plates = Plate.all

    @plates = @plates.where("meaning ~* ?", @query)

    @plates_sorted = @plates.sort_by(&:score).reverse if @sort_by == :score
    @plates_sorted = @plates.sort_by(&:score) if @sort_by == :score_least
    @plates_sorted = @plates.sort_by(&:created_at).reverse if @sort_by == :newest
    @plates_sorted = @plates.sort_by(&:created_at) if @sort_by == :oldest
    @plates = @plates_sorted

    @original_page = 1
    @original_page = params[:page].to_i if params[:page].to_i > 0

    @page = 0
    @page = ((params[:page].to_i - 1) * ITEMS_PER_PAGE) if params[:page].to_i > 0

    @plates = @plates[@page..@page + ITEMS_PER_PAGE - 1].to_a
  end

  # GET /plates/1 or /plates/1.json
  def show
  end

  # GET /plates/new
  def new
    @plate = Plate.new
  end

  def up
    if request.xhr?
      @plate = Plate.find_by(id: params[:id])
      @plate.score = @plate.score + 1
      @plate.save
      head :ok
    else
      head 500
    end
  end

  # POST /plates or /plates.json
  def create
    params.permit!
    @plate = Plate.new()
    @plate.meaning = params[:Body]
    if params[:NumMedia].to_i == 0
      render plain: "Image not provided"
      return
    end
    @plate.twilioimage = params[:MediaUrl0]
    @plate.score = 0
    
    @plate.save
    render plain: 'Plate submitted'
  end

  def new_img
    @plate = Plate.find_by(id: params[:id])
    render partial: "plates/new_img"
  end

  def add_new_img
    @plate = Plate.find_by(id: params[:id])
    File.write(Rails.root.join("tmpimg"), plate_params[:image].read, mode: "wb")
    @plate.images << File.read("tmpimg", mode: "rb").dump
    @plate.imageurls << "/plate_img/#{@plate.id}/#{@plate.images.length-1}"
    @plate.save

    redirect_to plate_path(@plate)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plate
      @plate = Plate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plate_params
      params.require(:plate).permit(:plate, :state, :image, :sort_by, :scope, :query, :page, :meaning)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def get_lic_plate
    send_data(Plate.find_by(id: params[:id]).image, filename: "plate")
  end
  def get_additional_lic_plate
    send_data(Plate.find_by(id: params[:id]).images[params[:num].to_i].undump, filename: "plate")
  end
  def get_blank_plate
    send_file(Rails.root.join("public", "state_license_plates", "#{params[:state]}.jpeg"))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plates_helper.rb
module PlatesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rate My Plate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'plates' %>
  </head>

  <body>
    <noscript>
      <div style="text-align:center;background-color:red;">
        <h1>
          Javascript is required to use most features of this website
        </h1>
      </div>
    </noscript> 

    <% sort_by_names = {score: "Highest voted", score_least: "Lowest voted", newest: "Newest", oldest: "Oldest"} %>
    <% scope_names = {"all" => "The United States", "AK"=>"Alaska", "AL"=>"Alabama", "AR"=>"Arkansas", "AS"=>"American Samoa", "AZ"=>"Arizona", "CA"=>"California", "CO"=>"Colorado", "CT"=>"Connecticut", "DC"=>"District of Columbia", "DE"=>"Delaware", "FL"=>"Florida", "GA"=>"Georgia", "GU"=>"Guam", "HI"=>"Hawaii", "IA"=>"Iowa", "ID"=>"Idaho", "IL"=>"Illinois", "IN"=>"Indiana", "KS"=>"Kansas", "KY"=>"Kentucky", "LA"=>"Louisiana", "MA"=>"Massachusetts", "MD"=>"Maryland", "ME"=>"Maine", "MI"=>"Michigan", "MN"=>"Minnesota", "MO"=>"Missouri", "MS"=>"Mississippi", "MT"=>"Montana", "NC"=>"North Carolina", "ND"=>"North Dakota", "NE"=>"Nebraska", "NH"=>"New Hampshire", "NJ"=>"New Jersey", "NM"=>"New Mexico", "NV"=>"Nevada", "NY"=>"New York", "OH"=>"Ohio", "OK"=>"Oklahoma", "OR"=>"Oregon", "PA"=>"Pennsylvania", "PR"=>"Puerto Rico", "RI"=>"Rhode Island", "SC"=>"South Carolina", "SD"=>"South Dakota", "TN"=>"Tennessee", "TX"=>"Texas", "UT"=>"Utah", "VA"=>"Virginia", "VI"=>"Virgin Islands", "VT"=>"Vermont", "WA"=>"Washington", "WI"=>"Wisconsin", "WV"=>"West Virginia", "WY"=>"Wyoming"} %>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Gr8Pl8</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to 'Send your plates to (309) A GR8 PL8', 'sms:+13092478758', class: "btn btn-success nav-link always_black" %>
            </li>

            <% if params[:controller] == "plates" && params[:action] == "index" %>

              <li class="nav-item">
                <%= link_to 'Highest voted', "?sort_by=score&scope=#{@scope}&query=#{@query}", class: "always_black btn btn-#{@sort_by == :score ? "primary" : "secondary"} nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Lowest voted', "?sort_by=score_least&scope=#{@scope}&query=#{@query}", class: "always_black btn btn-#{@sort_by == :score_least ? "primary" : "secondary"} nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Newest', "?sort_by=newest&scope=#{@scope}&query=#{@query}", class: "always_black btn btn-#{@sort_by == :newest ? "primary" : "secondary"} nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Oldest', "?sort_by=oldest&scope=#{@scope}&query=#{@query}", class: "always_black btn btn-#{@sort_by == :oldest ? "primary" : "secondary"} nav-link" %>
              </li>
              <!--
              <li class="nav-item dropdown">
                <div class="dropdown">
                  <button class="btn btn-secondary dropdown-toggle" type="button" id="stateSelect" data-bs-toggle="dropdown"  aria-expanded="false">
                    Select state: <%= scope_names[@scope.to_s] %>
                  </button>
                  <div class="dropdown-menu" aria-labelledby="stateSelect">
                    <%= render "plates/statelist" %>
                  </div>
                </div>
              </li>
              -->
            <% end %>

          </ul>

          <span class="tavbar-text" style="margin-right: 10px;">
            <%= link_to '<i class="bi bi-github"></i>'.html_safe, 'https://github.com/Matthiasclee/ratemyplate' %>
          </span>

          <%= form_with(url: "/plates", method: :get, class: "d-flex") do |form| %>
            <%= form.hidden_field :sort_by, value: @sort_by %>
            <%= form.hidden_field :scope, value: @scope %>

            <%= form.text_field :query, value: @query, class: "form-control me-2", placeholder: "Search" %>

            <%= form.submit :Search, class: "btn btn-outline-success", style: "display: inline-block;" %>
          <% end if params[:controller] == "plates" && params[:action] == "index" %>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/plates/_form.html.erb
<%= form_with(model: plate) do |form| %>
  <% if plate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plate.errors.count, "error") %> prohibited this plate from being saved:</h2>

      <ul>
        <% plate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :meaning %>
    <%= form.text_field :meaning, placeholder: "Meaning of plate" %>
  </div>

  <div class="field">
    <%= form.label :plate %>
    <%= form.text_field :plate, placeholder: "Exact plate number" %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plates/_new_img.html.erb
<%= form_with(model: @plate, url: new_plate_image_path(@plate), method: :post) do |form| %>
  <div class="field">
    
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit "Submit image", class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/plates/_plate.html.erb
<% plate = @plate %>
<tr>
  <td>
    <h1> <%= link_to '˄', up_plate_path(plate), class: "upvote", onclick: "addHrefToStorage('#{up_plate_path(plate)}')",remote: true %> </h1>
    <!-- ˅ -->
    <h2 id="<%= up_plate_path(plate) %>"> <%= plate.score %> </h2>
  </td>
  <td>

    <div id="c<%= plate.id.to_s %>" class="carousel slide" data-bs-interval="false">
      <div class="carousel-inner">
        <% if plate.meaning %>
          <h3 style="text-align:center;"> <%= plate.meaning %> </h3>
        <% end %>

        <img width="325px" src="<%= plate.twilioimage %>">

        <button class="carousel-control-prev" type="button" data-bs-target="#c<%= plate.id.to_s %>" data-bs-slide="prev">
        </button>

        <button class="carousel-control-next" type="button" data-bs-target="#c<%= plate.id.to_s %>" data-bs-slide="next">
        </button>
      </div>

  </td>
</tr>

app/views/plates/_statelist.html.erb
<h5 style = 'margin-top: 0px;'>
  <%= link_to 'All', "?sort_by=#{@sort_by}&scope=all&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Alaska', "?sort_by=#{@sort_by}&scope=AK&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Alabama', "?sort_by=#{@sort_by}&scope=AL&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Arkansas', "?sort_by=#{@sort_by}&scope=AR&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Arizona', "?sort_by=#{@sort_by}&scope=AZ&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'California', "?sort_by=#{@sort_by}&scope=CA&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Colorado', "?sort_by=#{@sort_by}&scope=CO&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Connecticut', "?sort_by=#{@sort_by}&scope=CT&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Washington D.C.', "?sort_by=#{@sort_by}&scope=DC&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Delaware', "?sort_by=#{@sort_by}&scope=DE&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Florida', "?sort_by=#{@sort_by}&scope=FL&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Georgia', "?sort_by=#{@sort_by}&scope=GA&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Hawaii', "?sort_by=#{@sort_by}&scope=HI&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Iowa', "?sort_by=#{@sort_by}&scope=IA&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Idaho', "?sort_by=#{@sort_by}&scope=ID&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Illinois', "?sort_by=#{@sort_by}&scope=IL&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Indiana', "?sort_by=#{@sort_by}&scope=IN&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Kansas', "?sort_by=#{@sort_by}&scope=KS&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Kentucky', "?sort_by=#{@sort_by}&scope=KY&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Louisiana', "?sort_by=#{@sort_by}&scope=LA&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Massachusetts', "?sort_by=#{@sort_by}&scope=MA&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Maryland', "?sort_by=#{@sort_by}&scope=MD&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Maine', "?sort_by=#{@sort_by}&scope=ME&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Michigan', "?sort_by=#{@sort_by}&scope=MI&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Minnesota', "?sort_by=#{@sort_by}&scope=MN&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Missouri', "?sort_by=#{@sort_by}&scope=MO&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Mississippi', "?sort_by=#{@sort_by}&scope=MS&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Montana', "?sort_by=#{@sort_by}&scope=MT&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'North Carolina', "?sort_by=#{@sort_by}&scope=NC&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'North Dakota', "?sort_by=#{@sort_by}&scope=ND&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Nebraska', "?sort_by=#{@sort_by}&scope=NE&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'New Hampshire', "?sort_by=#{@sort_by}&scope=NH&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'New Jersey', "?sort_by=#{@sort_by}&scope=NJ&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'New Mexico', "?sort_by=#{@sort_by}&scope=NM&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Nevada', "?sort_by=#{@sort_by}&scope=NV&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'New York', "?sort_by=#{@sort_by}&scope=NY&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Ohio', "?sort_by=#{@sort_by}&scope=OH&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Oklahoma', "?sort_by=#{@sort_by}&scope=OK&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Oregon', "?sort_by=#{@sort_by}&scope=OR&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Pennsylvania', "?sort_by=#{@sort_by}&scope=PA&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Rhode Island', "?sort_by=#{@sort_by}&scope=RI&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'South Carolina', "?sort_by=#{@sort_by}&scope=SC&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'South Dakota', "?sort_by=#{@sort_by}&scope=SD&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Tennessee', "?sort_by=#{@sort_by}&scope=TN&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Texas', "?sort_by=#{@sort_by}&scope=TX&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Utah', "?sort_by=#{@sort_by}&scope=UT&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Virginia', "?sort_by=#{@sort_by}&scope=VA&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Vermont', "?sort_by=#{@sort_by}&scope=VT&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Washington', "?sort_by=#{@sort_by}&scope=WA&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Wisconsin', "?sort_by=#{@sort_by}&scope=WI&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'West Virginia', "?sort_by=#{@sort_by}&scope=WV&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
  <%= link_to 'Wyoming', "?sort_by=#{@sort_by}&scope=WY&query=#{@query}", class: 'dropdown-item always_black', style: 'text-decoration: none;' %>
</h5>

app/views/plates/index.html.erb
<p id="notice"><%= notice %></p>
<% sort_by_names = {score: "Highest voted", score_least: "Lowest voted", newest: "Newest", oldest: "Oldest"} %>
<% scope_names = {"all" => "The United States", "AK"=>"Alaska", "AL"=>"Alabama", "AR"=>"Arkansas", "AS"=>"American Samoa", "AZ"=>"Arizona", "CA"=>"California", "CO"=>"Colorado", "CT"=>"Connecticut", "DC"=>"District of Columbia", "DE"=>"Delaware", "FL"=>"Florida", "GA"=>"Georgia", "GU"=>"Guam", "HI"=>"Hawaii", "IA"=>"Iowa", "ID"=>"Idaho", "IL"=>"Illinois", "IN"=>"Indiana", "KS"=>"Kansas", "KY"=>"Kentucky", "LA"=>"Louisiana", "MA"=>"Massachusetts", "MD"=>"Maryland", "ME"=>"Maine", "MI"=>"Michigan", "MN"=>"Minnesota", "MO"=>"Missouri", "MS"=>"Mississippi", "MT"=>"Montana", "NC"=>"North Carolina", "ND"=>"North Dakota", "NE"=>"Nebraska", "NH"=>"New Hampshire", "NJ"=>"New Jersey", "NM"=>"New Mexico", "NV"=>"Nevada", "NY"=>"New York", "OH"=>"Ohio", "OK"=>"Oklahoma", "OR"=>"Oregon", "PA"=>"Pennsylvania", "PR"=>"Puerto Rico", "RI"=>"Rhode Island", "SC"=>"South Carolina", "SD"=>"South Dakota", "TN"=>"Tennessee", "TX"=>"Texas", "UT"=>"Utah", "VA"=>"Virginia", "VI"=>"Virgin Islands", "VT"=>"Vermont", "WA"=>"Washington", "WI"=>"Wisconsin", "WV"=>"West Virginia", "WY"=>"Wyoming"} %>
<h3><%= sort_by_names[@sort_by] %> plates in <%= scope_names[@scope.to_s] %></h3>

<table>
  <tbody>
    <% @plates.each do |plate| %>
      <% @plate = plate %>
      <%= render partial: "plates/plate" %>
    <% end %>
  </tbody>
</table>
<h3 style="text-align: center;">
  <%= link_to '<-- Previous page', "?sort_by=#{@sort_by}&scope=#{@scope}&query=#{@query}&page=#{@original_page - 1}", class: "always_black btn btn-secondary" %>
  <%= @original_page %>
  <%= link_to 'Next page -->', "?sort_by=#{@sort_by}&scope=#{@scope}&query=#{@query}&page=#{@original_page + 1}", class: "always_black btn btn-secondary" %>
</h3>

<script>disableUpvotedPlates()</script>

app/views/plates/new.html.erb
<h1>New Plate</h1>

<%= render 'form', plate: @plate %>

<%= link_to 'Back', plates_path %>

app/views/plates/show.html.erb
<p id="notice"><%= notice %></p>
<% plate = @plate %>
<% state_names = {"AK"=>"Alaska", "AL"=>"Alabama", "AR"=>"Arkansas", "AS"=>"American Samoa", "AZ"=>"Arizona", "CA"=>"California", "CO"=>"Colorado", "CT"=>"Connecticut", "DC"=>"District of Columbia", "DE"=>"Delaware", "FL"=>"Florida", "GA"=>"Georgia", "GU"=>"Guam", "HI"=>"Hawaii", "IA"=>"Iowa", "ID"=>"Idaho", "IL"=>"Illinois", "IN"=>"Indiana", "KS"=>"Kansas", "KY"=>"Kentucky", "LA"=>"Louisiana", "MA"=>"Massachusetts", "MD"=>"Maryland", "ME"=>"Maine", "MI"=>"Michigan", "MN"=>"Minnesota", "MO"=>"Missouri", "MS"=>"Mississippi", "MT"=>"Montana", "NC"=>"North Carolina", "ND"=>"North Dakota", "NE"=>"Nebraska", "NH"=>"New Hampshire", "NJ"=>"New Jersey", "NM"=>"New Mexico", "NV"=>"Nevada", "NY"=>"New York", "OH"=>"Ohio", "OK"=>"Oklahoma", "OR"=>"Oregon", "PA"=>"Pennsylvania", "PR"=>"Puerto Rico", "RI"=>"Rhode Island", "SC"=>"South Carolina", "SD"=>"South Dakota", "TN"=>"Tennessee", "TX"=>"Texas", "UT"=>"Utah", "VA"=>"Virginia", "VI"=>"Virgin Islands", "VT"=>"Vermont", "WA"=>"Washington", "WI"=>"Wisconsin", "WV"=>"West Virginia", "WY"=>"Wyoming"} %>

<% if plate.meaning %>
  <h3> <%= plate.meaning %> </h3>
  <h5> <%= plate.plate %> </h5>
<% else %>
  <h3> <%= plate.plate %> </h3>
<% end %>

<h4>State: <%= state_names[plate.state] %> (<%= plate.state %>)</h4>
<h4>Spotted on: <%= plate.created_at.strftime("%m/%d/%Y") %> </h4>

<table>
  <tbody>
    <% @plate = plate %>
    <%= render partial: "plates/plate" %>
  </tbody>
</table>
<script>disableUpvotedPlates()</script>

<h3>Spotted it? submit another image!</h3>
<%= render partial: "plates/new_img" %>

<%= link_to 'Back', plates_path %>